
# Spirick Tuning
#
# A C++ class and template library
# for performance critical applications.
# Copyright (C) 1996-2023 Dietmar Deimling.
# All rights reserved.
# Internet  www.spirick.com
# E-Mail    info@spirick.com
#
# Version 1.49
# File makefile

PROJECTDIR = .
SUBDIR     = .

SUBDIRS    = tuning/ samples/ sourcedep/ topics/

include ./system.mak

clean::
	-$(RMDIR) $(TARGETDIR)
