
# Spirick Tuning
#
# The C++ class and template library
# for performance critical applications.
# Copyright (C) 1996-2021 Dietmar Deimling.
# All rights reserved.
# Internet  www.spirick.com
# E-Mail    info@spirick.com
#
# Version 1.48
# Date 11-20-2021
# File makefile

PROJECTDIR = .
SUBDIR     = .

SUBDIRS    = tuning/ samples/ sourcedep/

include ./system.mak

clean::
	-$(RMDIR) $(TARGETDIR)
