
# Spirick Tuning
#
# The C++ class and template library
# for performance critical applications.
# Copyright (C) 1996-2021 Dietmar Deimling.
# All rights reserved.
# Internet  www.spirick.com
# E-Mail    info@spirick.com
#
# Version 1.48
# Date 11-20-2021
# File tuning/chn/makefile

PROJECTDIR = ../..
SUBDIR     = tuning
DEPNAME    = chn

include ../subobjs.mak

USER_OBJS  = $(CHN_OBJS)

include ../../system.mak
